## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import TriggerEditor.SCArchive as sca;
from TriggerEditor import SCArchive as sca
# (Line 2) import User.Info as user;
from User import Info as user
# (Line 3) import Variable as v;
import Variable as v
# (Line 6) const stats = PVariable();
stats = _CGFW(lambda: [PVariable()], 1)[0]
# (Line 7) const timer = PVariable();
timer = _CGFW(lambda: [PVariable()], 1)[0]
# (Line 9) const USER_STATUS = 1;
USER_STATUS = _CGFW(lambda: [1], 1)[0]
# (Line 10) const SCA_ERROR = 2;
SCA_ERROR = _CGFW(lambda: [2], 1)[0]
# (Line 11) const SAVE_START = 3;
SAVE_START = _CGFW(lambda: [3], 1)[0]
# (Line 12) const SAVE_END = 4;
SAVE_END = _CGFW(lambda: [4], 1)[0]
# (Line 13) const SAVE = 5;
SAVE = _CGFW(lambda: [5], 1)[0]
# (Line 14) const SAVE_DENY = 6;
SAVE_DENY = _CGFW(lambda: [6], 1)[0]
# (Line 15) const LOADING = 7;
LOADING = _CGFW(lambda: [7], 1)[0]
# (Line 16) const LOAD_END = 8;
LOAD_END = _CGFW(lambda: [8], 1)[0]
# (Line 17) const LOAD_GLOBAL = 9;
LOAD_GLOBAL = _CGFW(lambda: [9], 1)[0]
# (Line 18) const SCA_WAIT = 10;
SCA_WAIT = _CGFW(lambda: [10], 1)[0]
# (Line 20) function StatusBar() {
@EUDFunc
def StatusBar():
    # (Line 21) const cp = getcurpl();
    cp = f_getcurpl()
    # (Line 22) switch(stats[cp]) {
    EUDSwitch(stats[cp])
    # (Line 23) case 0:
    _t1 = EUDSwitchCase()
    # (Line 24) eprintln(" ");
    if _t1(0):
        f_eprintln(" ")
        # (Line 25) break;
        EUDBreak()
        # (Line 26) case USER_STATUS:
    _t2 = EUDSwitchCase()
    # (Line 27) eprintln("\x17X \x04: ", v.mouseX[cp], "  \x17Y \x04: ", v.mouseY[cp], "  ", user.openedInven[cp]);
    if _t2(USER_STATUS):
        f_eprintln("\x17X \x04: ", v.mouseX[cp], "  \x17Y \x04: ", v.mouseY[cp], "  ", user.openedInven[cp])
        # (Line 33) break;
        EUDBreak()
        # (Line 34) case SCA_ERROR:
    _t3 = EUDSwitchCase()
    # (Line 35) eprintln("\x07[SCA] \x08연결이 되어있지않습니다");
    if _t3(SCA_ERROR):
        f_eprintln("\x07[SCA] \x08연결이 되어있지않습니다")
        # (Line 36) timer[cp] += 1;
        _ARRW(timer, cp).__iadd__(1)
        # (Line 37) if(timer[cp] == 50) {
        if EUDIf()(timer[cp] == 50):
            # (Line 38) timer[cp] = 0;
            _ARRW(timer, cp) << (0)
            # (Line 39) stats[cp] = USER_STATUS;
            _ARRW(stats, cp) << (USER_STATUS)
            # (Line 40) }
            # (Line 41) break;
        EUDEndIf()
        EUDBreak()
        # (Line 42) case SAVE_START:
    _t5 = EUDSwitchCase()
    # (Line 43) eprintln("\x07[SCA] \x04저장 완료 문구가 뜰 때까지 게임을 \x08종료하지 마세요");
    if _t5(SAVE_START):
        f_eprintln("\x07[SCA] \x04저장 완료 문구가 뜰 때까지 게임을 \x08종료하지 마세요")
        # (Line 44) timer[cp] += 1;
        _ARRW(timer, cp).__iadd__(1)
        # (Line 45) if(timer[cp] == 40) {
        if EUDIf()(timer[cp] == 40):
            # (Line 46) timer[cp] = 0;
            _ARRW(timer, cp) << (0)
            # (Line 47) stats[cp] = SAVE;
            _ARRW(stats, cp) << (SAVE)
            # (Line 48) }
            # (Line 49) break;
        EUDEndIf()
        EUDBreak()
        # (Line 50) case SAVE_END:
    _t7 = EUDSwitchCase()
    # (Line 51) eprintln("\x07[SCA] \x04저장이 완료되었습니다");
    if _t7(SAVE_END):
        f_eprintln("\x07[SCA] \x04저장이 완료되었습니다")
        # (Line 52) timer[cp] += 1;
        _ARRW(timer, cp).__iadd__(1)
        # (Line 53) if(timer[cp] == 50) {
        if EUDIf()(timer[cp] == 50):
            # (Line 54) timer[cp] = 0;
            _ARRW(timer, cp) << (0)
            # (Line 55) stats[cp] = USER_STATUS;
            _ARRW(stats, cp) << (USER_STATUS)
            # (Line 56) }
            # (Line 57) break;
        EUDEndIf()
        EUDBreak()
        # (Line 58) case SAVE:
    _t9 = EUDSwitchCase()
    # (Line 59) eprintln("\x07[SCA] \x04저장중입니다");
    if _t9(SAVE):
        f_eprintln("\x07[SCA] \x04저장중입니다")
        # (Line 60) break;
        EUDBreak()
        # (Line 61) case SAVE_DENY:
    _t10 = EUDSwitchCase()
    # (Line 62) eprintln("\x07[SCA] \x04저장할 수 없는 지역입니다");
    if _t10(SAVE_DENY):
        f_eprintln("\x07[SCA] \x04저장할 수 없는 지역입니다")
        # (Line 63) timer[cp] += 1;
        _ARRW(timer, cp).__iadd__(1)
        # (Line 64) if(timer[cp] == 50) {
        if EUDIf()(timer[cp] == 50):
            # (Line 65) timer[cp] = 0;
            _ARRW(timer, cp) << (0)
            # (Line 66) stats[cp] = USER_STATUS;
            _ARRW(stats, cp) << (USER_STATUS)
            # (Line 67) }
            # (Line 68) break;
        EUDEndIf()
        EUDBreak()
        # (Line 69) case LOADING:
    _t12 = EUDSwitchCase()
    # (Line 70) eprintln("\x07[SCA] \x04슬롯 데이터를 불러오는 중입니다");
    if _t12(LOADING):
        f_eprintln("\x07[SCA] \x04슬롯 데이터를 불러오는 중입니다")
        # (Line 71) break;
        EUDBreak()
        # (Line 72) case LOAD_END:
    _t13 = EUDSwitchCase()
    # (Line 73) eprintln("\x07[SCA] \x04슬롯 데이터를 불러오는데 성공했습니다");
    if _t13(LOAD_END):
        f_eprintln("\x07[SCA] \x04슬롯 데이터를 불러오는데 성공했습니다")
        # (Line 74) timer[cp] += 1;
        _ARRW(timer, cp).__iadd__(1)
        # (Line 75) if(timer[cp] == 50) {
        if EUDIf()(timer[cp] == 50):
            # (Line 76) timer[cp] = 0;
            _ARRW(timer, cp) << (0)
            # (Line 77) stats[cp] = 0;
            _ARRW(stats, cp) << (0)
            # (Line 78) }
            # (Line 79) break;
        EUDEndIf()
        EUDBreak()
        # (Line 80) case LOAD_GLOBAL:
    _t15 = EUDSwitchCase()
    # (Line 81) eprintln("\x07[SCA] \x04버전 정보를 불러오는 중입니다");
    if _t15(LOAD_GLOBAL):
        f_eprintln("\x07[SCA] \x04버전 정보를 불러오는 중입니다")
        # (Line 82) break;
        EUDBreak()
        # (Line 83) case SCA_WAIT:
    _t16 = EUDSwitchCase()
    # (Line 84) eprintln("\x07[SCA] \x04연결을 기다리고 있습니다");
    if _t16(SCA_WAIT):
        f_eprintln("\x07[SCA] \x04연결을 기다리고 있습니다")
        # (Line 85) break;
        EUDBreak()
        # (Line 86) }
    # (Line 87) }
    EUDEndSwitch()
